### PR TITLE
Fix EditorConfigParser

### PR DESCRIPTION
**Pull request by junichi11**
PR for #48

### CODE REVIEW

**Comment by junichi11** [comment]
@bennyn Fixed. Could you confirm and merge it?
Thanks.

**Comment by bennyn** [comment]
Great that you wrote a fix! I build the plugin from your `patch-for-issue48` but when I am opening an `.editorconfig` file now, then I don't have any syntay highlighting for it. :( Also the Navigator does not seem to work anymore. Could you use the plugin successfully? @Yserz: Does the EditorConfig Editor work for you?

**Comment by junichi11** [comment]
It works in my environment.
ec-nb-pr53

**Comment by Yserz** [comment]
It's working fine here too.

Product Version: NetBeans IDE 8.0.1 (Build 201408251540)

**Comment by bennyn** [comment]
Ok! Thanks for testing! Then I will merge it. You both are running Mac OS, right?

**Pull request merged**
