### PR TITLE
Normalize line endings

### PR DESCRIPTION
**Pull request by Shredder121**
Sorry to start off with such a big commit, but I noticed that not all line endings were normalized.

### CODE REVIEW

**Comment by Shredder121** [comment]
It's at least a step in the right direction, I also do it on my projects :wink:

**Comment by bennyn** [comment]
Hello @Shredder121 and thank you for your contribution.

We have enforced line endings: https://github.com/welovecoding/editorconfig-netbeans/blob/master/.gitattributes#L4

So what was wrong with them?

**Comment by Shredder121** [comment]
Hi!
The [commit that introduced the normalization(or rather the enforcement of normalization)](https://github.com/welovecoding/editorconfig-netbeans/commit/6ac0b2d65e63917f62b54065e20c0fe4b80a455c) didn't actually normalize the line endings.
Has anything changed in the meantime? I can renormalize the line endings if you want.

**Comment by Shredder121** [comment]
Nothing has changed, so it should apply as-is.

**Comment by Shredder121** [comment]
It's better to normalize the line endings up front, otherwise the next change applied will introduce unnecessary whitespace changes.

**Comment by Shredder121** [comment]
So I take it that this change is not wanted?
When I cloned the repository initially, git said I had unstaged changes.
This will also happen to others, presumably.

**Pull request closed without merging**
